### ISSUE TITLE
Change Safari support to rolling

### ISSUE THREAD

**Issue by kategengler** [emberjs/tracking-polaris#15]
RFC going through stages https://github.com/emberjs/rfcs/pull/984

Safari support should change to be rolling as other browsers are in the existing browser support policy. Safari 12 should be deprecated as part of this targeting 6.0

**Comment by kategengler** [comment]
https://github.com/emberjs/rfcs/pull/1005 advancement of rfc

**Comment by NullVoxPopuli** [comment]
Oh hey, we did this!
https://github.com/ember-learn/ember-website/pull/1088/
